# Generated by Django 4.1.7 on 2023-04-08 17:15

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0015_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='path',
            field=models.ImageField(null=True, upload_to='static/avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
